config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'
  get 'home/about'
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
  def about
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  respond_to :html

  def index
    @pins = Pin.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 25)
    #respond_with(@pins)
  end

  def show
    #respond_with(@pin)
    @previous = Pin.where("id > ?", @pin.id).order("id ASC").first || Pin.first
    @next = Pin.where("id < ?", @pin.id).order("id DESC").first || Pin.last
  end

  def new
    @pin = current_user.pins.build
    #respond_with(@pin)
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
    #respond_with(@pin)
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    #@pin.update(pin_params)
    #respond_with(@pin)
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end
  
  def next_pin
   
  end

  def previous_pin
    @pin.where("id < ?", self.id).order("id DESC").first || @pin.last
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :name)
    end
    
    def correct_user
      @pin = current_user.pins.find_by(id:params[:id])
      redirect_to pins_path, notice: "You are not authorized to edit this pin." if @pin.nil?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Chase The Chalice', root_path, class: 'navbar-brand textshadow' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About The Chalice', home_about_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <li><%= link_to 'Join', new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Add Pin', new_pin_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/home/about.html.erb
<div class="jumbotron shadow">
    <h1>About The Chalice</h1>
    <p>It all started one late fancy night ago at the Swinomish Casino. One of us had ordered an Irish Mule. 
    Although I’d like to say that I’m rather experienced with my alcohol, I was not privy to this style of drink or the drink-ware that this tasty beverage would be served in.  
    I was ill prepared for the beautiful, shimmering, glorious container of booze and awesomeness.  
    Instantly, I knew we must have this cup, it would be ours. Our precious.  
    At the graciousness of our host failing to be keen enough to see us remove this cup from the dining room, we made off with our booty.  
    We joked that this cup had to be straight out of the Indiana Jones movies. It was more than a mere cup.  It was a Chalice.  
    Oh boy, did we ever party with The Chalice that night.  On a subsequent return to our favorite watering hole, we come up with the idea that The Chalice should accompany us on all of our travels. 
    It was at that moment that the idea of “Chase the Chalice” was born. This is our pinboard to place pictures with captions to chronicle the travels of The Chalice. 
    Check in regularly to Chase The Chalice and see where it has been.</p>
    <h2><em>Cheers!</em></h2>
    <h2><em>Dale</em></h2>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
    
    <h1>Welcome to My First Rails App</h1>
    <p>Soon, I shall be kicking some ass, wootertons!</p>
    <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
    <%= link_to 'About', home_about_path, class: 'btn btn-default' %>
    <!--Pretty cool shit!! -->    
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chase The Chalice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<%= render 'home/header' %>

<div class="container">
  
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  <%= yield %>  
  
</div>


</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Editing pin</h1>
    </div>
    <div class="panel-body">
        <%= render 'form' %>  
    </div>
    
    <div class="panel-footer">
        <%= link_to 'Show', @pin %> |
        <%= link_to 'Back', pins_path %>
    </div>
    
  
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
      <div class="box">
        <div class="panel panel-default shadow">
          <%= link_to image_tag(pin.image.url(:medium)), pin %><br/>
          <div class="panel-body">
            <%= pin.description %><br />
            <hr />
            <p>Created on <%= pin.created_at.strftime("%v") %> by <strong><%= pin.user.name if pin.user %></strong></p>
          </div>

          <div class="panel-footer">
            <% if pin.user == current_user %>
                <%= link_to 'Edit', edit_pin_path(pin) %><br/>
                <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %><br/>
            <% end %>
          </div>

          </div>
      </div>
  <% end %>
</div>
<div class="text-center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>New pin</h1>    
    </div>
    <div class="panel-body">
        <%= render 'form' %>   
    </div>
    

    <div class="panel-footer">
        <%= link_to 'Back', pins_path %>    
    </div>

</div>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <%= image_tag @pin.image.url(:large), class: 'shadow img-rounded img-responsive' %>
      </div>
      <div class="panel-body">
        <%= @pin.description %><br/>
        <%= @pin.user.name %><br/><hr />
        <p>Created on <%= @pin.created_at.strftime("%v") %> by <strong><%= @pin.user.name if @pin.user %></strong></p>
        <% if @pin.user == current_user %>
            <%= link_to 'Edit', edit_pin_path(@pin) %> |
        <% end %>
        <%= link_to 'Home', pins_path %>
        <div class="text-center">
          <%= link_to 'Previous', @previous %> | <%= link_to 'Next', @next %> 
        </div>
        
      </div>
    </div>
  </div>
</div>